module.exports = {
  ADD_FILE: 'ADD_FILE',
  CHANGE: 'CHANGE',
  SELECT_FILE: 'SELECT_FILE',
  SELECT_FRAME: 'SELECT_FRAME',
  SET_CANVAS_HEIGHT: 'SET_CANVAS_HEIGHT',
  SET_CANVAS_WIDTH: 'SET_CANVAS_WIDTH',
  SET_LEFT_FOR_SELECTED_FILE_FRAME: 'SET_LEFT_FOR_SELECTED_FILE_FRAME',
  SET_TOP_FOR_SELECTED_FILE_FRAME: 'SET_TOP_FOR_SELECTED_FILE_FRAME'
};
