module.exports = {
  ADD_FILE: 'ADD_FILE',
  ADD_FRAME: 'ADD_FRAME',
  CHANGE: 'CHANGE',
  SELECT_FILE: 'SELECT_FILE',
  SELECT_FRAME: 'SELECT_FRAME',
  SET_CANVAS_HEIGHT: 'SET_CANVAS_HEIGHT',
  SET_CANVAS_WIDTH: 'SET_CANVAS_WIDTH'
};
